# theme #1

theme: jekyll-theme-hacker

#--------------------------------------------------------

# theme #2

# remote_theme: pages-themes/modernist@v0.2.0
# plugins:
# - jekyll-remote-theme # add this line to the plugins list if you already have one

#--------------------------------------------------------

# theme #3

# remote_theme: pages-themes/midnight@v0.2.0
# plugins:
# - jekyll-remote-theme # add this line to the plugins list if you already have one